name: alleged-avarice-wordpress
recipe: wordpress
config:
  webroot: wordpress
  database: mysql
  php: '8.1'
  composer_version: 2-latest
  env_file:
    - ./.environment/env
services:
  appserver:
    volumes:
      - ./.environment:/app/wordpress/.environment
    run:
      - cp -r /app/wordpress/.environment/wp-config.php /app/wordpress/wp-config.php
tooling:
  composer:
    service: appserver
    cmd: /usr/local/bin/composer

