name: alleged-avarice-wordpress
recipe: wordpress
config:
  webroot: wordpress
  database: mysql
  php: '8.1'
  composer_version: 2-latest
  env_file:
    - ./environment/env
services:
  appserver:
    overrides:
      volumes:
        - ./environment:/app/wordpress/environment
      environment:
        - APP_NAME=wordpress
        - APP_ENV=local
        - DB_HOST=database
        - DB_PORT=3306
        - DB_DATABASE=wordpress
        - DB_USERNAME=wordpress
        - DB_PASSWORD=wordpress
    run:
      - wp core download --path=/app/wordpress
      - cp -r /app/wordpress/environment/wp-config.php /app/wordpress/wp-config.php
      - cp -r /app/wordpress/environment/composer.json /app/wordpress/composer.json
tooling:
  composer:
    service: appserver
    cmd: /usr/local/bin/composer
    dir: /app/wordpress

